apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-0
  namespace: default
spec:
  clusterIP: 10.105.142.100
  selector:
    statefulset.kubernetes.io/pod-name: postgres-0
  externalIPs:
  - 192.168.1.4
  externalTrafficPolicy: Local
  ports:
  - nodePort: 30430
    port: 5430
    protocol: TCP
    targetPort: 5432
  sessionAffinity: None
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-1
  namespace: default
spec:
  clusterIP: 10.105.142.101
  selector:
    statefulset.kubernetes.io/pod-name: postgres-1
  externalIPs:
  - 192.168.1.4
  externalTrafficPolicy: Local
  ports:
  - nodePort: 30431
    port: 5431
    protocol: TCP
    targetPort: 5432
  sessionAffinity: None
  type: LoadBalancer
