application:
  db:
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:password}
    r2dbc:
      host-rw: ${MASTER_DB_HOST:localhost}
      host-ro: ${CLUSTER_DB_HOST:localhost}
      port-rw: ${MASTER_DB_PORT:5432}
      port-ro: ${CLUSTER_DB_PORT:5432}
      database: ${DB_NAME:db}
      pool:
        connect-timeout: 500
        duration: 30000
        validation-depth: REMOTE
        validation-query: "SELECT 1"
  reactive:
    buffer-size: 128
    duration: 30000
    limit: 1000
  locale: "en_US"
  rest:
    user: "/user/api"
  security:
    strength: 12

logging:
  level:
    org.springframework: TRACE
    su.svn: TRACE

server:
  port: ${PORT:5000}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost/db}
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:password}
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 200
  profiles.active: production
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
  thymeleaf.mode: HTML
