application:
  db:
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:password}
    r2dbc:
      host: ${MASTER_DB_HOST:localhost}
      host-ro: ${CLUSTER_DB_HOST:localhost}
      port: ${MASTER_DB_PORT:3306}
      port-ro: ${MASTER_DB_PORT:3305}
      database: ${DB_NAME:db}
      pool.duration: 30000
  reactive.duration: 30000
  reactive.limit: 100
  locale: "en_US"
  rest:
    user: "/user/api"
  security:
    strength: 12

logging:
  level:
    org.springframework: INFO
    su.svn: INFO

server:
  port: ${PORT:5000}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost/db?reconnect=true}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 300
  profiles.active: production
  r2dbc:
    pool:
      enabled: true
      initial-size: 30
      max-size: 1010
  thymeleaf.mode: HTML
