application:
  locale: "en_US"
  db:
    username: ${DB_USER:dbuser}
    password: ${DB_PASS:password}
    r2dbc:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:3306}
      database: ${DB_NAME:db}
  security:
    strength: 12

logging:
  level:
    org.springframework: DEBUG
    su.svn: TRACE

server:
  port: 18081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost/db?reconnect=true}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  liquibase:
    enabled: false
  profiles.active: production
  r2dbc:
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  thymeleaf:
    reactive:
      max-chunk-size: 8192
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
