application:
  locale: "en_US"
  db:
    username: "dbuser"
    password: ${DB_PASS:password}
    jdbc:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST:localhost}:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    r2dbc:
      host: ${DB_HOST:localhost}
      database: "db"
  security:
    strength: 12

logging:
  level:
    org.springframework:
      web: DEBUG
      data.r2dbc: DEBUG

server:
  port: 18081

spring:
  liquibase:
    enabled: false
  thymeleaf:
    reactive:
      max-chunk-size: 8192
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
