apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-reads
  namespace: default
spec:
  clusterIP: 10.105.142.189
  externalIPs:
  - 192.168.1.1
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30699
    port: 3305
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer
