apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin = mysql-bin
    max_connections = 600
    gtid_mode = ON
    replicate-do-db = db
    log-slave-updates
    enforce-gtid-consistency
    innodb_buffer_pool_size = 805306368
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
    max_connections = 600
    gtid_mode = ON
    enforce-gtid-consistency
    replicate-do-db = db
    innodb_buffer_pool_size = 805306368
