apiVersion: v1
kind: Service
metadata:
  labels:
    app: galera
  name: galera
  namespace: default
spec:
  clusterIP: 10.105.142.189
  externalIPs:
  - 192.168.21.41
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30699
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: galera
  sessionAffinity: None
  type: LoadBalancer
