apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-0
  namespace: default
  labels:
    app: galera
    podindex: "0"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/datadir-galera-0/
  storageClassName: slow

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-1
  namespace: default
  labels:
    app: galera
    podindex: "1"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/datadir-galera-1/
  storageClassName: slow

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-2
  namespace: default
  labels:
    app: galera
    podindex: "2"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/datadir-galera-2/
  storageClassName: slow
